#ifndef __ENK_STRING_TBL_H__
#define __ENK_STRING_TBL_H__

#include  "Mig_Base.hpp"
#include  "MStrMngr.hpp"

extern const MCHAR** gGetStringTbl();
extern INT32U  gGetStrTblItemCount();


/// Stirng Index Defination
enum
{
	/// Common
	STR_BLANK,
	STR_STEP_GO,
	STR_STEP_EXIT,
	STR_STEP_ABORT_MEAS,
	STR_STEP_HCOPY,
	
	STR_DATE,
	STR_TIME,
	STR_SPEED,
	
	STR_Y,
	STR_N,

	STR_CHINESE,
	STR_ENGLISH,

  STR_STARTUP_CHECK,
  STR_STARTUP_ERROR,
  
	STR_LAST_CUTOFF,
	
	STR_QUALITITIVE,
	STR_QUALITATIVE,
	
	STR_MIXMODE_SLOW,
	STR_MIXMODE_MIDDLE,
	STR_MIXMOE_FAST,
	STR_MEASURE_MODE,
	STR_BLANK_MODE,
	STR_BLANK_POS,
	STR_CALCULATE_MODE,
	STR_STEPIN_MODE,
	STR_PLATE_SHAKE,

	STR_N_VALUE,
	STR_MEAN_VALUE,
	STR_CV_VALUE,
	STR_SD_VALUE,
	
	/// Main Page
	STR_MAIN_MODE,
	STR_MAIN_FAST_MODE,
	STR_MAIN_PROGRAMMING,
	STR_MAIN_PROGRAMLIST,
	STR_MAIN_DATA_LIST,
	STR_MAIN_SYS_SETUP,
	STR_MAIN_HOST_CONTROL,

	/// Programm Mode page
	STR_PPROGRAMEDIT_TITLE,
	STR_PPROGRAM_TEST,
	STR_PPROGRAM_NAME,
	STR_PPROGRAM_TYPE,
	STR_PPROGRAM_CUTOFF,
	STR_PPROGRAM_FILTER,
	STR_PPROGRAM_MAINFILTER,
	STR_PPROGRAM_REFERFILTER,
	STR_PPROGRAM_SLAVEFILTER,
	STR_PPROGRAM_NEWCUTOFF,
	STR_PPROGRAM_SAMPLES,
	STR_PPROGRAM_MEASURING,
	
	/// Sample page
	STR_PSAMPLEPLATE_TITLE,
	
	/// Scan Data Process Panel page
	STR_PPROCESS_TITLE,
	STR_PPROCESS_COMPUTE,
	STR_PPROCESS_EDIT,
	STR_PPROCESS_DELETE,
	STR_PPROCESS_SAVE,
	
	STR_PDATACOMPUTE_TIPS,
	STR_PDATACOMPUTE_SELECTCUTOFF,
	STR_PDATACOMPUTE_CONTROL_NC,
	STR_PDATACOMPUTE_CONTROL_PC,

	STR_PDELETECUTOFF_TITLE,
	STR_PDELETECUTOFF_TIPS,
	
	STR_PSAVECUTOFF_TITLE,
	STR_PSAVECUTOFF_SAVING_CUTOFF,
	
	
	/// Fast Mode Pages
	STR_PFAST_TITLE,
	STR_PFAST_WHOLEPLATE,
	STR_PFAST_COLUMNMONITOR,
	STR_PFAST_MULTIFILTER,
	STR_PFAST_KINETIC,

	/// Whole Plate set page
	STR_PWHOLE_TITLE,
	STR_PWHOLE_FILTER,
	STR_PWHOLE_WL,
	STR_PWHOLE_COLUMNS,
	STR_PWHOLE_MIX_TIME,
	STR_PWHOLE_MIX_MODE,

	STR_PWHOLE_MEAS_TITLE,
	STR_PWHOLE_MEAS_WL,
	STR_PWHOLE_REFER_WL,
	STR_PWHOLE_MEAS_ON,
	STR_PWHOLE_MEAS_COLUMN,
	
	STR_PWHOLE_REPORT_TITLE,
	STR_PWHOLE_REPORT_COLUMNS,
	STR_PWHOLE_REPORT_PLATE_INFO,

	/// Column Monitor
	STR_PCOLUMN_TITLE,
	STR_PCOLUMN_PERIOD, 
	
	STR_PCOLUMN_MONITOR_TITLE,
	STR_PCOLUMN_MONITOR_TIME,
	STR_PCOLUMN_MONITOR_COLUMN,
	STR_PCOLUMN_MONITOR_ABSORB,
	
	/// Kinetic 
	STR_PKINETIC_MODE_TITLE,
	STR_PKINETIC_MODE_PERIOD,

	/**
	 *  Programming function
	 */	
	STR_PPROGRAM_TITLE,
	STR_PPROGRAM_NEW,
	STR_PPROGRAM_EDIT,
	STR_PPROGRAM_DELETE,
	
	STR_PPROGRAM_DEL_TITLE,
	STR_PPROGRAM_DEL_PID,
	STR_PPROGRAM_DEL_DELALL,

	STR_PPROGRAM_NEW_TITLE,
	STR_PPROGRAM_EDIT_TITLE,
	STR_PPROGRAM_EDIT_NAME,
	STR_PPROGRAM_EDIT_MAIN_FILTER,
	STR_PPROGRAM_EDIT_SLAVE_FILTER,
	STR_PPROGRAM_EDIT_REF_FILTER,
	STR_PPROGRAM_EDIT_MODE,
	
	/// Qualititive page
	STR_PQUALITY_TITLE,
	STR_PQUALITY_UNIT,
	STR_PQUALITY_BLANKS,
	STR_PQUALITY_STD_COUNT,
	STR_PQUALITY_STD_REPT,
	STR_PQUALITY_SAMPLE_REPT,
	STR_PQUALITY_STD_NO,
	STR_PQUALITY_STD_CONC,
	STR_PQUALITY_STD_POS,
	
	/// Mixing Mode page
	STR_PMIXING_TITLE,
	STR_PMIXING_K_FACTOR,
	STR_PMIXING_TEMPRATURE,
	STR_PMIXING_TEMPRATURE_CHK,
	
	/// Curve select page
	STR_PCURVE_TITLE,
	STR_PCURVE_CURVE,
	STR_PCURVE_AXISX,
	STR_PCURVE_AXISY,
	STR_PCURVE_LINEAR,
	STR_PCURVE_SEGMENT,
	
	/// Qualitative page
	STR_PQUALITATIVE_TITLE,
	STR_PQUALITATIVE_NC,
	STR_PQUALITATIVE_CO,
	STR_PQUALITATIVE_LP,
	STR_PQUALITATIVE_PC,
	STR_PQUALITATIVE_HP,
	
	/// Cutoff page
	STR_PCUTOFF_TITLE,
	STR_PCUTOFF_CUTOFF,
	STR_PCUTOFF_P_GRAY,	
	STR_PCUTOFF_N_GRAY,	
	STR_PCUTOFF_FORMAT_PLUS,	
	STR_PCUTOFF_FORMAT_SUB,	
	STR_PCUTOFF_FORMAT_SCUTOFF,	

	/// Delete Protocol page
	STR_PDELETE_TIP_DELETING,
	STR_PDELETE_TIP_HEAD,
	STR_PDELETE_TIP_DELETED,
	/**
	 *  Reader Config
	 */
	STR_PCFG_TITLE,
	STR_PCFG_FILTER,
	STR_PCFG_TIME,
	STR_PCFG_SERIALPORT,
	STR_PCFG_PRINTER,
	STR_PCFG_MAINTENANCE,
	STR_PCFG_CHECK_PLATE,
	 
	/// Cfg Date-time-name page
	STR_PCFG_TIME_TITLE, 
	STR_DEV_DATE,
	STR_DEV_TIME,
	STR_DEV_LANGUAGE,
	STR_DEV_NAME,

	/// Cfg Filter Page
	STR_PCFGFILTER_TITLE,
	STR_FILTER_1,	 	
	STR_FILTER_2,	 	
	STR_FILTER_3,	 	
	STR_FILTER_4,	 	
	STR_FILTER_5,	 	
	STR_FILTER_6,	 	
	STR_FILTER_7,	 	
	STR_FILTER_8,	 
	
	/// Cfg Communication page
	STR_PCFG_COMMU_TITLE,
	STR_PCFG_COMMU_BAUD,

	/// Cfg Printer 
	STR_PCFG_PRINTER_TITLE,
	STR_PCFG_PRINTER_TYPE,
	STR_PCFG_PRINTER_INTERNAL,
	STR_PCFG_PRINTER_EXT,
	STR_PCFG_PRINTER_AUTOPRINT,
	STR_PCFG_PRINTER_MODE,
	STR_PCFG_PRINTER_MODE_STD,
	//STR_PCFG_PRINTER_MODE_STD,
	
	/// Cfg Maintenance
	STR_PCFG_CHECK_TITLE,
	STR_PCFG_CHECK_RUN,
	STR_PCFG_CHECK_POWER_ON,
	STR_PCFG_CHECK_CLEAR_TIME,
	
	STR_PCFG_SERVICETEST_TITLE,
	STR_PCFG_SERVICETEST_LAMP,
	STR_PCFG_SERVICETEST_FILTER,
	STR_PCFG_SERVICETEST_COLUMN,
	STR_PCFG_SERVICETEST_AVERAGING,
	
	/// Cfg Plate Check
	STR_PCFG_PLATECHECK_TITLE,
	STR_PCFG_PLATECHECK,

		/**
	 *  Computer controlling
	 */	
	STR_PPCMODE_TITLE,
	STR_PPCMODE_SCAN_OPTION,
	STR_PPCMODE_MXING_TIME,
	STR_PPCMODE_MIXING_MODE,
	STR_PPCMODE_SECOND,
	STR_PPCMODE_START_COLUMN,
	STR_PPCMODE_COLUMN_COUNT,
	STR_PPCMODE_HINT_TESTING,
	STR_PPCMODE_HINT_TESTED,
	
};



#endif // __ENK_STRING_TBL_H__

